/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as AnalysisSatIdRouteImport } from './routes/analysis.$satId'
import { Route as SandboxSatIdRouteImport } from './routes/sandbox.$satId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisSatIdRoute = AnalysisSatIdRouteImport.update({
  id: '/analysis/$satId',
  path: '/analysis/$satId',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxSatIdRoute = SandboxSatIdRouteImport.update({
  id: '/sandbox/$satId',
  path: '/sandbox/$satId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/monitoring': typeof MonitoringRoute
  '/analysis/$satId': typeof AnalysisSatIdRoute
  '/sandbox/$satId': typeof SandboxSatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/monitoring': typeof MonitoringRoute
  '/analysis/$satId': typeof AnalysisSatIdRoute
  '/sandbox/$satId': typeof SandboxSatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/monitoring': typeof MonitoringRoute
  '/analysis/$satId': typeof AnalysisSatIdRoute
  '/sandbox/$satId': typeof SandboxSatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/history'
    | '/monitoring'
    | '/analysis/$satId'
    | '/sandbox/$satId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/history'
    | '/monitoring'
    | '/analysis/$satId'
    | '/sandbox/$satId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/history'
    | '/monitoring'
    | '/analysis/$satId'
    | '/sandbox/$satId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  MonitoringRoute: typeof MonitoringRoute
  AnalysisSatIdRoute: typeof AnalysisSatIdRoute
  SandboxSatIdRoute: typeof SandboxSatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$satId': {
      id: '/analysis/$satId'
      path: '/analysis/$satId'
      fullPath: '/analysis/$satId'
      preLoaderRoute: typeof AnalysisSatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/$satId': {
      id: '/sandbox/$satId'
      path: '/sandbox/$satId'
      fullPath: '/sandbox/$satId'
      preLoaderRoute: typeof SandboxSatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  MonitoringRoute: MonitoringRoute,
  AnalysisSatIdRoute: AnalysisSatIdRoute,
  SandboxSatIdRoute: SandboxSatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
